### ISSUE TITLE
Build error for php7

### ISSUE THREAD

**Issue by whatvn** [51Degrees/Device-Detection#10]
Hi, 

I am trying to get this module built for php7, what I have done so far is: 

1. Install php7 from source
2. Install swig newest release `3.0.12`
3. Build 51Degrees php7 extension (pattern): 
```bash
$ /php7/bin/phpize
$ ./configure PHP7=1 --with-php-config=/php7/bin/php-config
$ make
```

And then this error(s) showed up: 

```c
g++ -I. -I/root/sources/Device-Detection/php/pattern -DPHP_ATOM_INC -I/root/sources/Device-Detection/php/pattern/include -I/root/sources/Device-Detection/php/pattern/main -I/roo
t/sources/Device-Detection/php/pattern -I/php7/include/php -I/php7/include/php/main -I/php7/include/php/TSRM -I/php7/i
nclude/php/Zend -I/php7/include/php/ext -I/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/sources/Device-Detection/php/pattern/src/pa
ttern/51Degrees_PHP.cpp  -fPIC -DPIC -o src/pattern/.libs/51Degrees_PHP.o
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp: In function ‘void SWIG_FAIL()’:
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp:1024:27: error: ‘FiftyOneDegreesPatternV3_globals’ was not declared in this scope
 #define SWIG_ErrorCode() (FiftyOneDegreesPatternV3_globals.error_code)
                           ^
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp:1030:16: note: in expansion of macro ‘SWIG_ErrorCode’
     zend_error(SWIG_ErrorCode(), "%s", SWIG_ErrorMsg());
                ^
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp: In function ‘void SWIG_ResetError()’:
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp:1023:26: error: ‘FiftyOneDegreesPatternV3_globals’ was not declared in this scope
 #define SWIG_ErrorMsg() (FiftyOneDegreesPatternV3_globals.error_msg)
                          ^
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp:1039:3: note: in expansion of macro ‘SWIG_ErrorMsg’
   SWIG_ErrorMsg() = default_error_msg;
   ^
/root/sources/Device-Detection/php/pattern/src/pattern/51Degrees_PHP.cpp: In function ‘void _wrap_new_MapStringString__SWIG_1(zend_execute_data*, zval*)’:
```

How can i fix this? 

Thank,

**Comment by Joseph51D** [comment]
Hi @whatvn 

We're sorry to hear your having issues.

Can you tell me a little more about your environment?

- g++ version
- PHP version (7.0/7.1)
- OS + version

Thank you,
Joseph

**Comment by whatvn** [comment]
Thank for quick response, our environment specs is: 

- php 7.0.13
- G++ 4.8.2 
- Centos 6.9 (final) 

Thank,

**Comment by whatvn** [comment]
same issue happens with php 7.1.5, on same environment

**Comment by Joseph51D** [comment]
Hi @whatvn 

Sorry for the delay. When using the same version of CentOS and G++, I haven't been able to re-create the issue you are seeing, but instead of installing php from source I used this guide here: https://tecadmin.net/install-php-7-on-centos/ 

Need **php70w** & **php70w-devel**

I'll try installing PHP from source to see if i can re-create the issue that way.

Regards,

Joe

**Comment by Joseph51D** [comment]
Hi @whatvn 

Were you able to resolve this? Let me know either way.

Regards,
Joe

**Comment by andywolk** [comment]
This may help "[PHP] Use ZEND_MODULE_GLOBALS_ACCESSOR to access globals":
> https://github.com/swig/swig/commit/224bb9e0232a219b7cefd23472b592b39e277f46

So use swig-master or as a workaround go to auto-generated 51Degrees_PHP.cpp and replace 
`(FiftyOneDegreesPatternV3_globals.`
with
`ZEND_MODULE_GLOBALS_ACCESSOR(FiftyOneDegreesPatternV3,`
