### ISSUE TITLE
Nginx Scope for 51D_match_all directive

### ISSUE THREAD

**Issue by stuartio** [51Degrees/Device-Detection#11]
Currently this is scoped to only the location context, which means you must include the directive for every single path in your Nginx config. It would be super useful to have this available at the http,server,location and possibly even if in location contexts.

**Comment by ben51degrees** [comment]
@stuartio 
This is something which we have implemented and will be included in the next release. I will make sure to update this issue when we release the change.

Regards,
Ben.
