### ISSUE TITLE
Nginx headers

### ISSUE THREAD

**Issue by stgleb** [51Degrees/Device-Detection#14]
Hello, right now I can see following headers in instructions

``` 
add_header x-device $http_x_device;
add_header x-mobile $http_x_mobile;
add_header x-tablet $http_x_tablet;
add_header x-smartphone $http_x_smartphone;
add_header x-metrics $http_x_metrics;
```

Is there any  other headers? Like hardwareModel, hardwareFamily, browserName etc. ?

**Comment by michael51degrees** [comment]
Hi there,

you can add your own headers based on our property dictonary. for example

```
51D_match_all x-HM HardwareModel

add_header x-HM $http_x_HM
```
