### ISSUE TITLE
[nginx module] How to change the User-Agent

### ISSUE THREAD

**Issue by fan51degrees** [51Degrees/Device-Detection#15]
1. Is it possible to change the User-Agent before the 51Degrees module starts detection device?

2. At which phase(nginx) does 51Degrees module starts detection?

**Comment by lily51degrees** [comment]
Hi there,

1. 51degrees pulls the User-Agent from the http headers of the requesting device. if you wish to make changes to the User-Agent, you could modify the ngx_http_51D_module.c to change the User-Agent before you perform device detection on it.

2. I shall confirm ASAP for you and update this post with the answer.

Many thanks,

Lily

**Comment by Joseph51D** [comment]
Hi @fan51degrees 

In answer to question 2, the 51Degrees module is added to the `NGX_HTTP_REWRITE_PHASE` array.

Regards,

Joe
