### ISSUE TITLE
Cannot use hash trie data file on Node.js 8.9.3 using module version 3.2.18-dev

### ISSUE THREAD

**Issue by prachaquanttech** [51Degrees/Device-Detection#22]
using this config

 ```
const fiftyonedegreescoreConfig = {

  dataFile: 'static/51degrees/51Degrees-EnterpriseV3.4.trie',
  properties: [
    'HardwareVendor', 
    'HardwareModel', 
    'HardwareFamily', 
    'PriceBand', 
    'PlatformName', 
    'PlatformVersion', 
    'ScreenPixelsHeight', 
    'ScreenPixelsWidth',
    'ReleaseMonth',
    'ReleaseYear',
    'DeviceType',
    'HardwareModelVariants',
  ],
  cacheSize: 10000,
  poolSize: 20,
}
const provider = DeviceDetection.provider(fiftyonedegreescoreConfig) //Error was throw here
const match =  provider.getMatch(ctx.header['user-agent'])
match.close()
```

`
Error: Illegal arguments for construction of _exports_Provider
`
Please help

**Comment by prachaquanttech** [comment]
Update
if I remove  properties, cacheSize and poolSize from the config, Code will run fine.

**Comment by JoshGrew51D** [comment]
Hi There

You should only need to remove poolSize as this is a Pattern only option. Hash Trie does not have a workset pool like Pattern. It's matches consist of Device offsets which are smaller than Pattern worksets. As a result they are calculated on the fly.

Let me know how you get on.

**Comment by prachaquanttech** [comment]
Thanks for the answer
if add "properties" option back, It will throw "segmentation fault".

**Comment by JoshGrew51D** [comment]
Which version of the data file are you using currently?

**Comment by prachaquanttech** [comment]
51Degrees-EnterpriseV3.4.trie

**Comment by JoshGrew51D** [comment]
Of course, sorry ignore me.

I have modified the example above with some changes to the configuration. Properties are not stored as an array but as a comma separated string. The keys in the config are also surrounded by quotes. 

Try this and let me know what you get back.

Would you also be able to send over the code where you reference the Device Detection module in: `DeviceDetection.provider`

```
const fiftyonedegreescoreConfig = {'dataFile' : 'static/51degrees/51Degrees-EnterpriseV3.4.trie',
    'properties' : 'HardwareVendor,HardwareModel,HardwareFamily,PriceBand,PlatformName,PlatformVersion,ScreenPixelsHeight,ScreenPixelsWidth,ReleaseMonth,ReleaseYear,DeviceType,HardwareModelVariants'}

const provider = DeviceDetection.provider(fiftyonedegreescoreConfig)
const match =  provider.getMatch(ctx.header['user-agent'])
match.close()
```

**Comment by prachaquanttech** [comment]
This code work
```
const fiftyonedegreescoreConfig = {'dataFile' : 'static/51degrees/51Degrees-EnterpriseV3.4.trie',
    'properties' : 'HardwareVendor,HardwareModel,HardwareFamily,PriceBand,PlatformName,PlatformVersion,ScreenPixelsHeight,ScreenPixelsWidth,ReleaseMonth,ReleaseYear,DeviceType,HardwareModelVariants'}

const provider = DeviceDetection.provider(fiftyonedegreescoreConfig)
const match =  provider.getMatch(ctx.header['user-agent'])
match.close()
```
BTW we use module this in Koa.js. Can I write ```provider.getMatch(ctx.request)``` like in Express.js?
Thanks a lot
