### ISSUE TITLE
Varnish Device-Detection module crashes with OperaMini custom request headers

### ISSUE THREAD

**Issue by turric4n** [51Degrees/Device-Detection#29]
Hi,

We have a Varnish (varnish-4.1.10 revision 1d090c5a08f41c36562644bafcce9d3cb85d824f)
production environment with 51Degrees device detection module installed (last version and last database) handmade compiled. 
99% of received request are working fine but a simple request can made the service crash...  
We found that Opera-Mini for Android send a lot of custom headers per request and some of this headers make 52Degrees to crash (SegFault).

Backtrace :
`                                         "Assert error in child_signal_handler(), mgt/mgt_child.c line 296:
                                           Condition(Signal 11 (Segmentation fault) received at (nil) si_code 128) not true.
                                         thread = (cache-worker)
                                         version = varnish-4.1.10 revision 1d090c5a08f41c36562644bafcce9d3cb85d824f
                                         ident = Linux,4.4.0-87-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
                                         now = 96182.163202 (mono), 1543491228.981447 (real)
                                         Backtrace:
                                           0x4346c1: pan_ic+0x191
                                           0x454f2c: varnishd() [0x454f2c]
                                           0x7f95cdbf0390: libpthread.so.0(+0x11390) [0x7f95cdbf0390]
                                           0x7f95bd9f8320: libvmod_fiftyonedegrees.so(fiftyoneDegreesGetHttpHeaderCount+0) [0x7f95bd9f8320]
                                           0x7f95bd9f5e14: libvmod_fiftyonedegrees.so(setImportantHeaders+0x54) [0x7f95bd9f5e14]
                                           0x7f95bd9f5fe9: libvmod_fiftyonedegrees.so(vmod_match_all+0x69) [0x7f95bd9f5fe9]
                                           0x7f95c1dd023c: vgc.so(VGC_function_vcl_recv+0x3fc) [0x7f95c1dd023c]
                                           0x440b9c: vcl_call_method+0x1fc
                                           0x442eba: VCL_recv_method+0x5a
                                           0x437f0e: CNT_Request+0xcfe
`

Problematic Request Headers :

`                                               \"X-Clacks-Overhead: GNU ph\",
                                               \"X-OperaMini-Phone-UA: Mozilla/5.0 (Linux; Android 6.0; MYA-L03 Build/HUAWEIMYA-L03; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.
                                               \"X-OperaMini-Features: advanced, camera, download, file_system, folding, httpping, pingback, routing, touch, viewport\",
                                               \"X-OperaMini-Phone: Android #\",`

You can try to reproduce this error sending a GET request to a document with some of above headers.

**Comment by JoshGrew51D** [comment]
Sorry to hear you are having issues. I've tested using our example and I am able to retrieve a response without the SegFault.

Could you send over the code where you implement 51Degrees so we can try to replicate more closely with your environment?

**Comment by turric4n** [comment]
Hi Josh, thanks for your fast response 👍 

Here is our VCL implementation of 51Degrees :

`
    # 51degrees opera mini temporal patch
    if (req.http.Device-Stock-UA || req.http.X-OperaMini-Phone-UA) {
      unset req.http.Device-Stock-UA;
      unset req.http.X-OperaMini-Phone-UA;
    }
    # 51degrees recon
    set req.http.X-DeviceType = fiftyonedegrees.match_all("DeviceType");

    if (req.http.X-DeviceType == "SmartPhone") {
      set req.http.X-UA-Device = "mobile";
    }
    else
    {
      set req.http.X-UA-Device = "desktop";
    }
`

As you can see above we applied some logic to avoid the crash :

`    if (req.http.Device-Stock-UA || req.http.X-OperaMini-Phone-UA) {
      unset req.http.Device-Stock-UA;
      unset req.http.X-OperaMini-Phone-UA;
    }`

If we don't apply this logic process crashes.

**Comment by JoshGrew51D** [comment]
Thanks for sending that over. From playing with our example.vcl running on 4.1.10 I am still unable to replicate it supplying the same headers and properties.

I think the best way to go forward would be to arrange a call so we can review first hand, is this a feasible option for you? 

If you drop us an Email at support@51degrees.com we can arrange something for Monday.

Let me know.

**Comment by JoshGrew51D** [comment]
Just following up to see if you have had a chance to look at my last message. Hopefully we can get this working for you.

**Comment by JoshGrew51D** [comment]
Closing this for the time being as we are unable to replicate the issue. Please get in touch and I will be happy to re-open.

**Comment by turric4n** [comment]
Thanks, no problem... We put some conditionals under VCL to keep it working again. Thanks Josh.
