### ISSUE TITLE
Could not build pattern with GCC 8

### ISSUE THREAD

**Issue by creadone** [51Degrees/Device-Detection#34]
With gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10) i could not build pattern, was getting errors like this:

```
src/http/modules/ngx_http_proxy_module.c: In function ‘ngx_http_proxy_init_headers’:
src/http/modules/ngx_http_proxy_module.c:3528:22: error: cast between incompatible function types from ‘size_t (*)(ngx_http_script_engine_t *)’ {aka ‘long unsigned int (*)(struct <anonymous> *)’} to ‘void (*)(ngx_http_script_engine_t *)’ {aka ‘void (*)(struct <anonymous> *)’} [-Werror=cast-function-type]
         copy->code = (ngx_http_script_code_pt) ngx_http_script_copy_len_code;
```

It solved with workaround from official repo, [see changeset](https://trac.nginx.org/nginx/changeset/9e25a5380a21240cdb66646f1e20ef7247b646a1/nginx). Replace the source files to changed files from nginx repo and the pattern will be compiled.

**Comment by JoshGrew51D** [comment]
Thanks for sending over the changeset link. We will take a look at changing the default Nginx source version to prevent this happening.
