### ISSUE TITLE
Inconsistent results, unable to detect device type.

### ISSUE THREAD

**Issue by joeyhub** [51Degrees/Device-Detection#35]
I've tried this with the latest chrome.

```
51D_match_all x-device-type DeviceType;
51D_match_all x-desktop IsDesktop;
51D_match_all x-tablet IsTablet;
51D_match_all x-mobile IsMobile;
```

These return NA, NA, NA and False respectively using a recent trie data file.

**Comment by joeyhub** [comment]
Your product is inaccurately describe. You should fix that immediately.

![image](https://user-images.githubusercontent.com/1512978/57884725-3e8a0f80-7821-11e9-8c54-6760a1e19563.png)

![image](https://user-images.githubusercontent.com/1512978/57884813-785b1600-7821-11e9-9c76-8420e351293c.png)

**Comment by joeyhub** [comment]
![image](https://user-images.githubusercontent.com/1512978/57884968-d0921800-7821-11e9-927f-de1d2dd66245.png)

You withdrew a free feature but you haven't updated all of your pages.

**Comment by JoshGrew51D** [comment]
I'm afraid that DeviceType has never been available as part of the On Premise Lite data file. The Lite data that is distributed using our Cloud service is intentionally different.

We will look at the naming of these different subscriptions to try and avoid confusion going forward.

**Comment by joeyhub** [comment]
Ah yes I see the issue, it's easy with the hover to accidentally jump to cloud and not realise. You also wouldn't expect it to be a different product, just a different hosting solution.

**Comment by JoshGrew51D** [comment]
Closing this issue for now - any other questions just get in touch.
