### ISSUE TITLE
Get random match of UA by platform and platform version

### ISSUE THREAD

**Issue by sashayakovtseva** [51Degrees/Device-Detection#47]
Hello,

I am trying to use the trie go binding to generate UA strings that will match particular os and os version. 
Can find a way to do this so far, is it even possible?

**Comment by Steve51D** [comment]
Hi @sashayakovtseva, Apologies for the delay in getting back to you.

I'm afraid our API does not have the ability to return User-Agents that match a specific set of properties (or generate them).
It might be possible for us to supply this information as a one-off though if you are still interested?

**Comment by sashayakovtseva** [comment]
@Steve51D yes, that will be helpful

**Comment by Steve51D** [comment]
Closing this as it is being handled directly by our customer success team and doesn't relate to any issues with the software.
