### ISSUE TITLE
Can't update submodules

### ISSUE THREAD

**Issue by LorenzoPantano** [51Degrees/Device-Detection#49]
Hi,
I'm facing an error while cloning the repository with the submodules.
While the cloning with:
`git clone --recurse-submodules https://github.com/51Degrees/device-detection-cxx.git`
The error:
`Fetched in submodule path 'src/common-cxx', but it did not contain 54de38e846f9974f21259ac8ed5e25ee3a5410f0. Direct fetching of that commit failed.`

So I tried to manually download the common-cxx from the common repository and put it manually in the src/common-cxx folder. But building the whole solution, even with the Visual Studio Solution didn't work giving me errors of any kind such as missing semicolons, definitions not found, etc. I'm guessing that putting the common folder manually is not the right way to proceed. So how can I resolve this problem?
Sorry, maybe I'm not understanding how to deal with this very well, but I'm developing a web server in C and I need to go on with this great service.

Thanks in advice.

**Comment by Steve51D** [comment]
Hi @LorenzoPantano,

Apologies for this, it looks like device-detection-cxx has been updated at some point without the corresponding changes to common-cxx being pushed to the public master branch.

I've now updated the branch so you should be able to just fetch the missing commit.

**Comment by LorenzoPantano** [comment]
Hi, now the clone with submodules works fine. 
Thank you
